### ISSUE TITLE
メディアタグの扱いを仕様変更。

### ISSUE THREAD

**Issue by pooza** [pooza/mulukhiya-toot-proxy#1493]
設定値 `/tagging/media/enable` で切り替え。デフォルトは`true`。
### 有効にする場合の例
```
tagging:
  media:
    enable: true
    tags:
      image: image
      video: video
      audio: audio
```
### 無効の場合の例
```
tagging:
  media:
    enable: false
```
